In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('chypoxia_expression_all.txt', sep='\t')
df.head()

,GeneName,ERR507061,ERR507060,ERR507062,ERR507057,ERR507058,ERR507063,SRR1177128,SRR1177127,SRR1533836,...,SRR11906302,SRR11906301,SRR11906300,SRR11906299,SRR12094725,SRR12094724,SRR12094723,SRR12094722,SRR12094721,SRR12094720
0,A1BG,37.283742,63.076096,58.359220,51.835799,63.200916,77.089779,64.999615,38.976929,5.385791,...,29.101212,5.430488,9.794114,5.790424,30.944794,71.590944,84.000271,35.762386,46.654185,49.689273
1,A1CF,0.208250,0.128505,0.105848,0.571935,0.097768,0.182546,0.452059,0.442067,0.546556,...,0.122583,0.111621,1.725806,0.000000,0.106503,0.220271,0.457867,0.331004,0.445765,0.419399
2,A2M,0.000000,0.370055,0.178863,0.559960,0.000000,0.482627,0.000000,0.000000,0.202035,...,0.000000,6.223053,0.000000,0.000000,1.057511,0.898652,1.094939,1.582168,1.479448,0.737190
3,A2ML1,1.936194,4.224028,2.036041,4.025681,0.486712,0.189829,18.509968,10.880497,1.331895,...,2.264054,1.845892,0.259315,0.734109,6.646888,7.479593,16.735734,13.180330,17.208330,13.041850
4,A3GALT2,0.000000,0.964735,0.928569,1.968339,0.000000,0.879576,0.000000,0.000000,1.268565,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [3]:
df.describe()

,ERR507061,ERR507060,ERR507062,ERR507057,ERR507058,ERR507063,SRR1177128,SRR1177127,SRR1533836,SRR1533838,...,SRR11906302,SRR11906301,SRR11906300,SRR11906299,SRR12094725,SRR12094724,SRR12094723,SRR12094722,SRR12094721,SRR12094720
count,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,1.964300e+04,1.964300e+04,1.964300e+04,1.964300e+04,...,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,1.964300e+04,19643.000000,1.964300e+04,1.964300e+04
mean,667.627710,678.389392,671.728805,689.971757,676.269459,656.854776,2.580638e+03,2.553049e+03,1.189501e+03,1.139865e+03,...,970.143082,915.077272,887.611416,932.676200,1678.646285,2100.739336,2.548790e+03,1800.072197,2.541258e+03,2.424415e+03
std,6365.585597,7021.084957,6588.460454,7063.064805,7267.244424,7856.991780,2.439183e+04,3.205918e+04,1.521498e+04,1.368717e+04,...,7989.643129,9217.892707,9114.174121,8662.237157,13686.929992,17146.850669,2.073669e+04,13107.494240,1.848810e+04,1.739872e+04
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
25%,1.094582,1.538485,1.120952,1.756244,0.877495,1.189776,3.584194e+00,2.728220e+00,2.565085e+00,1.255977e+00,...,0.239944,0.959463,0.500064,0.000000,1.596267,2.427992,2.913787e+00,1.464848,2.520577e+00,2.349535e+00
50%,59.028222,64.154332,58.184344,65.350346,45.130565,42.347890,2.025040e+02,1.944145e+02,1.044604e+02,7.217838e+01,...,60.961735,58.397185,56.019595,49.416116,107.050288,152.913124,1.835024e+02,123.489605,1.867029e+02,1.812998e+02
75%,318.190951,321.586776,319.638906,326.453611,269.615099,237.312057,1.077046e+03,1.071764e+03,5.598681e+02,4.959776e+02,...,342.165742,343.490003,313.424269,300.235753,617.541944,832.494275,9.992730e+02,753.339430,1.091939e+03,1.046702e+03
max,713085.410893,803234.562526,732342.454828,803072.771909,834967.009944,923305.848629,1.718836e+06,3.478330e+06,1.851942e+06,1.636468e+06,...,444270.309676,799042.299200,714053.297914,496276.903482,633723.308249,815504.568481,1.113139e+06,765200.202049,1.081374e+06,1.062567e+06

In [4]:
HN = pd.read_csv('HN-pair.csv', sep=',')
HN.head()

      hypoxia    normoxia
0  SRR1037318  SRR1037316
1  SRR1037317  SRR1037315
2  SRR1037314  SRR1037312
3  SRR1037313  SRR1037311
4  SRR1037310  SRR1037308

In [5]:
HNratio = pd.DataFrame()
HNratio["GeneName"] = df["GeneName"] 
for i in range(len(HN)):
    h = str(HN.iloc[i,0])
    n = str(HN.iloc[i,1])
#    c = str(h) +"/"+str(n)
    HNratio[h] = (df.loc[:,h] + 1)/(df.loc[:,n] +1)
    HNratio.append(HNratio)
HNratio.head()

,GeneName,SRR1037318,SRR1037317,SRR1037314,SRR1037313,SRR1037310,SRR1037309,SRR1999315,SRR1999314,SRR1999313,...,SRR3096877,SRR3535659,SRR3535663,SRR3535667,SRR3535671,SRR3535675,SRR3535679,SRR3535683,SRR3535687,SRR3535691
0,A1BG,0.882145,1.149552,1.643580,0.961810,3.003729,1.313112,0.752687,1.760707,2.493335,...,2.128821,2.124226,3.132407,3.091951,3.090319,1.000000,2.440165,14.878706,15.996222,17.481703
1,A1CF,0.826244,0.963785,0.945125,1.378708,1.042645,0.929528,0.533085,0.391134,0.412622,...,1.000000,2.878588,0.902912,2.670307,1.409328,1.299240,1.136231,0.296580,0.080040,0.783737
2,A2M,1.010762,1.000000,1.000000,1.000000,4.242209,1.000000,0.901560,0.280491,1.418973,...,0.572119,1.606225,0.224179,1.292923,1.299972,0.224179,1.009528,1.000000,0.224179,1.000000
3,A2ML1,0.723338,1.203949,0.988296,0.790603,0.758996,0.471396,0.805394,1.032650,2.032740,...,0.843263,0.632821,1.120936,1.300955,1.168951,0.782956,0.531443,1.072824,0.782956,0.691384
4,A3GALT2,1.000000,1.000000,1.000000,1.000000,0.235511,1.000000,3.896546,0.178776,1.000000,...,2.498563,1.000000,0.717374,1.000000,1.000000,0.418113,1.000000,1.000000,0.137788,1.000000

In [6]:
HNratio_ = HNratio.set_index('GeneName')

HNratiolog2 = HNratio_.apply(np.log2)
HNratiolog2 = HNratiolog2.reset_index()
HNratiolog2.head()

,GeneName,SRR1037318,SRR1037317,SRR1037314,SRR1037313,SRR1037310,SRR1037309,SRR1999315,SRR1999314,SRR1999313,...,SRR3096877,SRR3535659,SRR3535663,SRR3535667,SRR3535671,SRR3535675,SRR3535679,SRR3535683,SRR3535687,SRR3535691
0,A1BG,-0.180912,0.201072,0.716842,-0.056177,1.586755,0.392990,-0.409878,0.816155,1.318077,...,1.090055,1.086937,1.647272,1.628517,1.627756,0.000000,1.286979,3.895177,3.999659,4.127774
1,A1CF,-0.275359,-0.053217,-0.081424,0.463317,0.060248,-0.105430,-0.907563,-1.354267,-1.277107,...,0.000000,1.525361,-0.147342,1.417006,0.495007,0.377668,0.184256,-1.753506,-3.643138,-0.351558
2,A2M,0.015444,0.000000,0.000000,0.000000,2.084816,0.000000,-0.149505,-1.833975,0.504847,...,-0.805612,0.683674,-2.157276,0.370637,0.378481,-2.157276,0.013681,0.000000,-2.157276,0.000000
3,A2ML1,-0.467257,0.267774,-0.016985,-0.338974,-0.397837,-1.084988,-0.312234,0.046351,1.023425,...,-0.245945,-0.660130,0.164704,0.379571,0.225214,-0.352997,-0.912012,0.101413,-0.352997,-0.532441
4,A3GALT2,0.000000,0.000000,0.000000,0.000000,-2.086135,0.000000,1.962196,-2.483777,0.000000,...,1.321099,0.000000,-0.479203,0.000000,0.000000,-1.258036,0.000000,0.000000,-2.859479,0.000000

In [7]:
HNratiolog2.describe()

,SRR1037318,SRR1037317,SRR1037314,SRR1037313,SRR1037310,SRR1037309,SRR1999315,SRR1999314,SRR1999313,SRR1999312,...,SRR3096877,SRR3535659,SRR3535663,SRR3535667,SRR3535671,SRR3535675,SRR3535679,SRR3535683,SRR3535687,SRR3535691
count,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,...,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000,19643.000000
mean,-0.017696,0.271345,-0.231217,0.030395,0.372908,-0.255588,-0.438112,-0.227012,0.061582,0.357984,...,-0.655563,0.603133,-0.307460,1.345348,0.732306,-0.042749,0.136891,0.144858,-0.417686,1.336802
std,0.907330,0.928315,0.760390,0.762983,0.789972,0.694781,0.883123,0.796288,0.742597,0.703916,...,1.299454,0.668080,0.612552,0.944867,0.731986,0.616982,0.571662,1.063949,1.030246,1.187518
min,-7.858349,-7.124291,-8.305175,-8.135878,-5.541382,-7.549388,-7.863209,-7.957398,-6.383701,-5.902220,...,-11.060840,-5.554727,-7.920039,-5.588457,-6.609757,-7.920039,-8.872930,-6.940927,-9.363174,-5.588457
25%,-0.447377,-0.098470,-0.613315,-0.283277,0.000000,-0.595182,-0.858788,-0.603120,-0.255794,0.000000,...,-1.455503,0.000000,-0.501965,0.329521,0.000000,-0.193772,0.000000,-0.357311,-1.036210,0.016824
50%,0.000000,0.038101,-0.262201,0.000000,0.291392,-0.245895,-0.308910,-0.064725,0.000000,0.237481,...,-0.482118,0.716466,-0.340916,1.711219,0.850625,0.000000,0.081746,0.000000,-0.285051,1.361956
75%,0.223286,0.573630,0.000000,0.184939,0.663325,0.000000,0.000000,0.024977,0.377889,0.680514,...,0.000000,0.949412,0.000000,1.941689,1.141781,0.065883,0.266241,0.577247,0.000000,2.116767
max,8.211777,8.721185,7.897211,7.890468,9.528952,6.304507,9.015157,5.922304,6.886107,8.195852,...,8.763788,6.579506,6.267698,8.872930,9.055452,8.146879,8.572596,9.864031,6.857085,9.124766

In [8]:
HNratiolog2.set_index('GeneName').to_csv("HN-ratio_log2.csv", sep=",")

In [ ]:
HNratio.set_index('GeneName').to_csv("HN-ratio.csv", sep=",")